USE [master]
GO
/****** Object:  Database [MeetupEvent]    Script Date: 27.05.2019 14:23:33 ******/
CREATE DATABASE [MeetupEvent]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MeetupEvent', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MeetupEvent.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MeetupEvent_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\MeetupEvent_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MeetupEvent] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MeetupEvent].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MeetupEvent] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MeetupEvent] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MeetupEvent] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MeetupEvent] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MeetupEvent] SET ARITHABORT OFF 
GO
ALTER DATABASE [MeetupEvent] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MeetupEvent] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MeetupEvent] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MeetupEvent] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MeetupEvent] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MeetupEvent] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MeetupEvent] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MeetupEvent] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MeetupEvent] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MeetupEvent] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MeetupEvent] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MeetupEvent] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MeetupEvent] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MeetupEvent] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MeetupEvent] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MeetupEvent] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MeetupEvent] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MeetupEvent] SET RECOVERY FULL 
GO
ALTER DATABASE [MeetupEvent] SET  MULTI_USER 
GO
ALTER DATABASE [MeetupEvent] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MeetupEvent] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MeetupEvent] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MeetupEvent] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MeetupEvent] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'MeetupEvent', N'ON'
GO
ALTER DATABASE [MeetupEvent] SET QUERY_STORE = OFF
GO
USE [MeetupEvent]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 27.05.2019 14:23:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryID] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[CategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Event]    Script Date: 27.05.2019 14:23:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Event](
	[EventID] [int] IDENTITY(1,1) NOT NULL,
	[EventName] [nvarchar](50) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ApplicationDate] [datetime] NOT NULL,
	[Subscribers] [int] NOT NULL,
	[EventImage] [nvarchar](255) NOT NULL,
	[CategoryID] [int] NOT NULL,
	[PersonID] [int] NOT NULL,
 CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED 
(
	[EventID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Message]    Script Date: 27.05.2019 14:23:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Message](
	[MessageID] [int] IDENTITY(1,1) NOT NULL,
	[MessageBy] [int] NOT NULL,
	[MessageTo] [int] NOT NULL,
	[MessageDate] [datetime] NOT NULL,
	[Message] [nvarchar](300) NOT NULL,
 CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED 
(
	[MessageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 27.05.2019 14:23:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[PersonID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[DateOfBirth] [date] NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Event]  WITH CHECK ADD  CONSTRAINT [FK_Event_Categories] FOREIGN KEY([CategoryID])
REFERENCES [dbo].[Categories] ([CategoryID])
GO
ALTER TABLE [dbo].[Event] CHECK CONSTRAINT [FK_Event_Categories]
GO
ALTER TABLE [dbo].[Event]  WITH CHECK ADD  CONSTRAINT [FK_Event_Person] FOREIGN KEY([PersonID])
REFERENCES [dbo].[Person] ([PersonID])
GO
ALTER TABLE [dbo].[Event] CHECK CONSTRAINT [FK_Event_Person]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_Person] FOREIGN KEY([MessageBy])
REFERENCES [dbo].[Person] ([PersonID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_Person]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_Person1] FOREIGN KEY([MessageTo])
REFERENCES [dbo].[Person] ([PersonID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_Person1]
GO
USE [master]
GO
ALTER DATABASE [MeetupEvent] SET  READ_WRITE 
GO
